### ISSUE TITLE
PiP control issues

### ISSUE THREAD

**Issue by xx90three** [Naezr/ShyFox#198]
Hi there

I just reinstalled the ShyFox to the 3.8.1 version because of some UI issues in the old version and the PiP media control seems to be missing the progress bar, volume and I can't double click to fullscreen.
![Screenshot 2024-11-14 045209](https://github.com/user-attachments/assets/550d76d9-9dc0-4f9f-ae4c-50f711c54f37)

I reinstall the backup chrome and it's back to normal
![Screenshot 2024-11-14 045027](https://github.com/user-attachments/assets/bdc015aa-2a05-4f31-afab-406f682ef6f4)

Not sure if I'm doing something wrong or it's a bug.
Firefox 132.0.2

**Comment by maly6254** [comment]
Noticing the same, any insight?

**Comment by xx90three** [comment]
> Noticing the same, any insight?

No luck yet

**Comment by Flat** [comment]
in shy-global.css
```css
/* some z-index */
#navigator-toolbox {z-index: 2 !important;}
#browser {z-index: 1 !important;}
```
This is the style that breaks it.
