### ISSUE TITLE
context menu arrow button

### ISSUE THREAD

**Issue by JoyHak** [Naezr/ShyFox#57]
Стрелка вверху контекстного меню имеет кривую границу и очень неудобная. Её можно где-то пофиксить или полностью убрать?

https://github.com/Naezr/ShyFox/assets/156242738/c5bfb885-60ec-4cd8-8ed7-5de27e949726

**Comment by Naezr** [comment]
Обычно такие стрелки появляются, если контекстное меню настолько длинное, что в экран не влезает. Я встречался с похожей проблемой на линуксе с Wayland - тогда по какой-то причине это включалось тогда, когда меню открыто посреди экрана и места под все пункты хватало. С обновлениями системы прошло. Прошу заметить - системы, а не самого браузера. Но то было именно что скроллящееся контекстное меню на линуксе, а тут стрелочка теребится на Windows. 

Попробуй закомментить секцию `CONTEXT MENU` в `shy-compact.css`

**Comment by JoyHak** [comment]
> Обычно такие стрелки появляются, если контекстное меню настолько длинное, что в экран не влезает. Я встречался с похожей проблемой на линуксе с Wayland - тогда по какой-то причине это включалось тогда, когда меню открыто посреди экрана и места под все пункты хватало. С обновлениями системы прошло. Прошу заметить - системы, а не самого браузера. Но то было именно что скроллящееся контекстное меню на линуксе, а тут стрелочка теребится на Windows.
> 
> Попробуй закомментить секцию `CONTEXT MENU` в `shy-compact.css`

Нашел способ пофиксить :))

```css
menupopup > :is(menuitem, menu){
    font-size: 13px !important;     
    height: fit-content !important;
    border-radius: var(--rounding) !important;
    margin: 0 !important;
}
```
