### ISSUE TITLE
Catppuccin control buttons

### ISSUE THREAD

**Issue by JoyHak** [Naezr/ShyFox#75]
Улучшение темы путем изменения стиля кнопок управления окном. Теперь браузер един с моей темой в системе.

https://github.com/Naezr/ShyFox/assets/156242738/1ef8ce7b-7e60-4dab-9ce9-d3421c445bf6

![Снимок экрана (9)](https://github.com/Naezr/ShyFox/assets/156242738/a0790f26-eca7-467e-a869-22ba7fcb47c7)

```CSS
/*== ShyFox Window Controls =========================================================================================================================

Styles for Min Max Close buttons


--- BUTTONS POSITION ---------------------------------------------------------------------------------------------------------------------------

*/

.titlebar-buttonbox-container{
  position: fixed !important;
  overflow: clip !important;

  z-index: -1 !important;
  
  transition: var(--transition) !important;
  
  /* set position to right */
  right: 0px;
  top: 8px;
}

/* 

--- CATPUCCIN CONTROLS ----------------------------------------------------------------------------------------------------------------------------------

*/

/* Buttons container override */ 
.titlebar-button {
	transition: all 0.3s ease !important;
	padding: 8px 10px !important;
    background: var(--bg-col) !important; /* container background: must be defined */
}
.titlebar-button > .toolbarbutton-icon {
	transition: all 0.3s ease !important;
	list-style-image: none;
	border-radius: 10px;
}

/* Minimize (left) button */
.titlebar-button.titlebar-min > .toolbarbutton-icon {
	background: #fae3b0 !important;
}

/* Maximize & restore (middle) button */
.titlebar-button.titlebar-max > .toolbarbutton-icon,
.titlebar-button.titlebar-restore > .toolbarbutton-icon {
	background: #ddb6f2 !important;
}

/* Close (right) button */
.titlebar-button.titlebar-close > .toolbarbutton-icon {
	background: #f28fad !important;
}

/* Mouse hover effect: visible when you mouse over them. Defined as color but can be some icon or image... */
.titlebar-button:hover > .toolbarbutton-icon {
	background: var(--bg-col) !important;
}
```
